version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    image: asia-docker.pkg.dev/architect-certification-289902/backend/backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@my-postgres-postgresql.database.svc.cluster.local:5432/postgres
    volumes:
      - shared_data:/app/data
    networks:
      - app_network

  user-frontend:
    build:
      context: .
      dockerfile: docker/user-frontend.Dockerfile
    image: asia-docker.pkg.dev/architect-certification-289902/user-frontend/user-frontend:latest
    ports:
      - "8502:8502"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app_network

  admin-frontend:
    build:
      context: .
      dockerfile: docker/admin-frontend.Dockerfile
    image: asia-docker.pkg.dev/architect-certification-289902/admin-frontend/admin-frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app_network

volumes:
  shared_data:

networks:
  app_network:
    driver: bridge

