apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: backend
      context: backend
      buildpacks:
        builder: paketobuildpacks/builder-jammy-base
    - image: admin-frontend
      context: admin-frontend
      buildpacks:
        builder: paketobuildpacks/builder-jammy-base
    - image: user-frontend
      context: user-frontend
      buildpacks:
        builder: paketobuildpacks/builder-jammy-base
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
