apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
        - name: admin-frontend
          image: admin-frontend
          command: ["streamlit", "run", "admin-frontend/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
spec:
  selector:
    app: admin-frontend
  ports:
    - port: 8501
      targetPort: 8501
  type: ClusterIP
