apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: langgraph-mcp-agents
data:
  # LangSmith Settings
  LANGSMITH_TRACING: "true"
  LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
  LANGSMITH_PROJECT: "LangGraph-MCP-Agents"
  
  # Authentication
  USE_LOGIN: "false"
  USER_ID: "admin"
  USER_PASSWORD: "admin123"
  
  # Database
  DATABASE_URL: "sqlite:///./shared_data.db"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "multi_agent"
  DB_USER: "postgres"
  DB_PASSWORD: "admin123"
  
  # Server Settings
  BACKEND_URL: "http://backend-service:8000"
  BACKEND_WEBSOCKET: "ws://backend-service:8000"
  USER_FRONTEND_URL: "http://user-frontend-service:8501"
  ADMIN_FRONTEND_URL: "http://admin-frontend-service:8502"
  BACKEND_PORT: "8000"
  USER_FRONTEND_PORT: "8501"
  ADMIN_FRONTEND_PORT: "8502"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
  namespace: langgraph-mcp-agents
data:
  mcp_config.json: |
    {
      "mcpServers": {
        "get_current_time": {
          "description": "시간 확인 도구",
          "command": "python",
          "args": ["mcp_server_time.py"],
          "transport": "stdio"
        }
      }
    }

---
# ==================================================
# 17. ConfigMap for System Prompts
# ==================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: prompts-config
  namespace: langgraph-mcp-agents
data:
  system_prompt.yaml: |
    system_prompt: |
      You are a helpful AI assistant powered by LangGraph and equipped with various tools through the Model Context Protocol (MCP).
      
      Your capabilities include:
      - Accessing external data sources and APIs through MCP tools
      - Performing calculations, searches, and data retrievals
      - Maintaining conversation context and memory
      - Providing accurate and helpful responses
      
      When using tools:
      1. Choose the most appropriate tool for the task
      2. Explain what you're doing when using tools
      3. Provide clear and comprehensive responses based on tool results
      4. If a tool fails, explain the issue and suggest alternatives
      
      Always be helpful, accurate, and transparent about your capabilities and limitations.
