apiVersion: v1
kind: Service
metadata:
  name: user-frontend-lb
  namespace: langgraph-mcp-agents
  labels:
    app: user-frontend
  annotations:
    cloud.google.com/load-balancer-type: "External"
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: user-frontend
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-lb
  namespace: langgraph-mcp-agents
  labels:
    app: admin-frontend
  annotations:
    cloud.google.com/load-balancer-type: "External"
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: admin-frontend
  ports:
  - port: 80
    targetPort: 8502
    protocol: TCP
    name: http
    
---
apiVersion: v1
kind: Service
metadata:
  name: backend-lb
  namespace: langgraph-mcp-agents
  labels:
    app: backend
  annotations:
    cloud.google.com/load-balancer-type: "External"
    networking.gke.io/load-balancer-type: "External"
    # WebSocket 지원을 위한 LoadBalancer 설정
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
