apiVersion: v1
kind: Secret
metadata:
  name: anthropic-api-key
type: Opaque
stringData:
  ANTHROPIC_API_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
type: Opaque
stringData:
  OPENAI_API_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: langsmith-api-key
type: Opaque
stringData:
  LANGSMITH_API_KEY: ""
