version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  gateway-app:
    build:
      context: .
      dockerfile: docker/gateway-app.Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app_network

  api-gateway:
    build:
      context: .
      dockerfile: docker/api-gateway.Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - gateway-app
    networks:
      - app_network

  backend-worker:
    build:
      context: .
      dockerfile: docker/backend-worker.Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - app_network

  user-frontend:
    build:
      context: .
      dockerfile: docker/user-frontend.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api-gateway
    environment:
      - BACKEND_URL=http://api-gateway
    networks:
      - app_network

  admin-frontend:
    build:
      context: .
      dockerfile: docker/admin-frontend.Dockerfile
    ports:
      - "8502:8502"
    depends_on:
      - api-gateway
    environment:
      - BACKEND_URL=http://api-gateway
    networks:
      - app_network

volumes:
  shared_data:

networks:
  app_network:
    driver: bridge
